### ISSUE TITLE
nonceが加算されない

### ISSUE THREAD

**Issue by gentarok** [gentarok/ZaifApiWrapper#19]
ApiClient.PostAsync()メソッド実行時にループを例外で脱出した場合、その後のAPI呼び出しで「nonce not incremented」が返される現象を確認

**Comment by gentarok** [comment]
一度発生したが、再現せず
実際に投げたnonceの値が１度目と２度目でどう変化していたか（していなかったか）は不明
ロガーを仕込む必要があるかもしれない

**Comment by gentarok** [comment]
公式ドキュメントに
>nonce not incremented
>
>    前回API実行時よりnonce値が加算されていません。nonce値はAPI実行ごとに加算してください。
>    複数プロセス・スレッドからAPIコールを使用している場合、終了を待ったり、APIキーを使い分けるなどの工夫をしてください。

と記載されているので、ひょっとすると同一APIキーから複数のPostリクエスト送るとnonceの値に関わらずエラーになるんだろうか？
それなら、Postの処理全体をlockしてしまうのもアリかもしれない
↓
試してみたらビンゴくさい

**Comment by gentarok** [comment]
一発目のPOSTで正常終了のレスポンスを受け取った直後に二発目を投げても「nonce not incremented」が出た。（当然nonceは増加させてた）
どうやら、連続リクエストをする時にはちょっと待つ必要があるみたい。

**Comment by taylorcammack** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
lingate, @xuantinfx, @simonbarrow121, @chiadi, @antonmdv, @rzhb, @bedri, @Dominic-Schlegel, @Khanchai59, @Alfredo-Saucedo, @alytvynov, @wuyan516, @malzzz, @lsysun1, @Black-J08, @dyzne, @bfortuner, @sefaaydin, @Originalmenace, @GeekWorkCode, @qinix, @LaksahanWijerathne, @xcv58, @learn-the, @horizon13th, @MdEmon889, @abhishekgahlot, @ionaryu, @sunsweet, @ccampbell, @apzentral, @omenyayl, @liangchenio, @DanielDaCosta, @sumkey, @xbj126, @farshidtorkaman, @letusfly85, @zhr5210, @claudsk33, @saiw, @1337-44, @reddavis, @unitwk, @xiaomin0322, @yoratoni, @JimAmuro, @thainquet, @TyJackson, @rgvuralivankia, @senolc, @bvolpato, @arden, @dragopress, @joelquek, @phelma, @rhaicode, @Coinpocalypse, @wars2, @scottycc, @LEECHHE, @muhaozhang, @marlovich, @farukonder, @sinand99, @dendisuhubdy, @thomasklemm, @LoveOrange, @jnacier, @noprom, @dboland77, @chenjinnanjiuzhang, @WyattSanders, @dotuanson, @wingofsky, @mabodx, @mingrui, @orok-orok, @siwilizhao, @LawrenceHan, @Lexion13, @wsbblyy, @jiku, @sbhadade, @JasonDRZ, @wenwuwu, @hg-gong, @lvdou-bing, @mirzap, @Louis0723, @Skyker25, @guilhrmefp, @ciotas, @TheLevti, @wdragow, @lioneljr45, @minty99, @mattNest, @webcaetanoalexruperez, @aquinault, @blombard, @tuananhht94, @tangh18, @Rance29, @Nanodash, @jhkuperus, @yifeil, @volvinbur1, @kenfehling, @rabbitix, @jianjin712, @khajavi, @TheLevti, @zzq889, @Ranal, @EMichaelC, @yangfan0095, @raozhiyong11, @Mark-Wu, @tomkenig, @trentbrooks, @augiaugi, @deju, @itsusony, @alvaro-jmp, @gessichen, @sorinmagureanu, @MonkeyWaffle0, @ahembal, @felipsandoval, @nibu147, @JehPark, @zhenxinlei, @sjyMystery, @arttbergg, @johnefemer, @jhlater, @stick-wth, @kishorechk, @myset, @TheElse, @liuying3013, @kenjitu, @Duanminlang, @pooyagolchian, @Olegshipu95, @leo19920923, @PepijnTlhw1392724402, @jonarrien, @RexLittle, @zigzagway, @blacklig, @Chrustpl, @TimothyL96, @fredfeng0326, @daltonjorge, @cryptofetish, @HayderAlbayati2020, @skaptox, @tohnee, @lucasbento, @lucasprates, @Z-Beatles, @modster, @sonpython, @pkliang, @phuongnl, @MajjiR, @GendSmith, @pxzero, @cgezenler, @Portaecha168, @oiovoyo, @VG101, @farhan711, @sugiki, @thomas4019, @tangible-idea, @orilee, @Dqddyvillager1722, @ctkqiang, @Perados, @marcosDuque, @tatianilima, @countcain, @OzzOnn76, @eliquious, @Identity9165, @zhaohui-yang, @caguana122, @n-dragon, @nnsitem, @pistatium, @wobudapai, @xuhongliang, @Shellnco, @tangweikun
